name: Deploy to AWS Elastic Beanstalk

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install awsebcli

      - name: Run tests
        id: tests
        run: |
          pytest -v

      # Powiadomienie o sukcesie testów
      - name: Email - Testy się udały
        if: success() && steps.tests.conclusion == 'success'
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          secure: true
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: "Testy się udały - ${{ github.repository }}"
          to: ${{ vars.EMAIL_SENDTO}}
          from: ${{ vars.EMAIL_MAILFROM}}
          body: |
            Testy się udały!
            
            Projekt: ${{ github.repository }}
            Branch: ${{ github.ref_name }}
            Commit: ${{ github.event.head_commit.message }}
            Autor: ${{ github.actor }}
            Data: ${{ github.event.head_commit.timestamp }}
            
            Wszystkie testy przeszły pomyślnie.

      # Powiadomienie o błędzie testów
      - name: Email - Testy się nie udały
        if: failure() && steps.tests.conclusion == 'failure'
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          secure: true
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: "Testy się nie udały - ${{ github.repository }}"
          to: ${{ vars.EMAIL_SENDTO}}
          from: ${{ vars.EMAIL_MAILFROM}}
          priority: high
          body: |
            Testy się nie udały!
            
            Projekt: ${{ github.repository }}
            Branch: ${{ github.ref_name }}
            Commit: ${{ github.event.head_commit.message }}
            SHA: ${{ github.sha }}
            Autor: ${{ github.actor }}
            Data: ${{ github.event.head_commit.timestamp }}
            
            Sprawdź logi i popraw błędy.

      - name: Configure AWS credentials
        if: success()
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Deploy to Elastic Beanstalk
        id: deploy
        if: success()
        run: |
          eb init BG-BigData-Projekt-2025 -p python-3.13 --region ${{ vars.AWS_REGION }}
          eb deploy BG-BigData-Projekt-2025-env

      # Powiadomienie o sukcesie deployment'u
      - name: Email - Deployment się udał
        if: success() && steps.deploy.conclusion == 'success'
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          secure: true
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: "Deployment się udał - ${{ github.repository }}"
          to: ${{ vars.EMAIL_SENDTO}}
          from: ${{ vars.EMAIL_MAILFROM}}
          body: |
            Deployment się udał!
            
            Projekt: ${{ github.repository }}
            Branch: ${{ github.ref_name }}
            Commit: ${{ github.event.head_commit.message }}
            SHA: ${{ github.sha }}
            Autor: ${{ github.actor }}
            Data: ${{ github.event.head_commit.timestamp }}
            Environment: BG-BigData-Projekt-2025-env
            Region: ${{ vars.AWS_REGION }}
            
            Aplikacja została wdrożona na produkcję.

      # Powiadomienie o błędzie deployment'u
      - name: Email - Deployment się nie udał
        if: failure() && steps.deploy.conclusion == 'failure'
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          secure: true
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: "BŁĄD: Deployment się nie udał - ${{ github.repository }}"
          to: ${{ vars.EMAIL_SENDTO}}
          from: ${{ vars.EMAIL_MAILFROM}}
          priority: high
          body: |
            Deployment się nie udał!
            
            Projekt: ${{ github.repository }}
            Branch: ${{ github.ref_name }}
            Commit: ${{ github.event.head_commit.message }}
            SHA: ${{ github.sha }}
            Autor: ${{ github.actor }}
            Data: ${{ github.event.head_commit.timestamp }}
            Environment: BG-BigData-Projekt-2025-env
            Region: ${{ vars.AWS_REGION }}
            
            Wymagana natychmiastowa interwencja!
            Sprawdź logi: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}          
      
